version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: demo/Dockerfile.custom
    image: wagtail-demo-custom
    container_name: wagtail-demo
    ports:
      - "8000:8000"
    volumes:
      # Persist database
      - demo-db:/app/demo
    environment:
      - DJANGO_SETTINGS_MODULE=demo.settings.dev

volumes:
  demo-db:
