services:
  # Web service
  - type: web
    name: wagtail-demo
    env: docker
    dockerfilePath: ./demo/Dockerfile.custom
    dockerContext: .
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: demo.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: False
    plan: free

databases:
  - name: wagtail-db
    databaseName: wagtail_demo
    user: wagtail_demo
    plan: free
